#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int i=1;
	int light_val=0;
	int dark_val=0;
	int threshold=0;


	while (i==1)
	{
		displayCenteredTextLine(3,"Press enter on the light surface");
		if (getButtonPress(buttonEnter))
		{
			light_val=SensorValue(S3);
			setLEDColor(ledGreen);	//indicate value taken
			sleep(500);
			setLEDColor(ledOff);	//turn off LED
			i++;	//exit while loop
		}  //end if

	}  //end while


	while (i==2)
	{
		displayCenteredTextLine(3,"Press enter on the dark surface");


		if (getButtonPress(buttonEnter))
		{
			dark_val=SensorValue(S3);	//Assign dark value
			setLEDColor(ledRed);	//indicate value taken
			sleep(500);
			setLEDColor(ledOff);	//turn off LED
			i++;	//exit while loop
		}  //end if


	}  //end while

	//Output Feedback
	threshold=(light_val+dark_val)/2;

	displayCenteredTextLine(6,"Threshold is %d", threshold);
	displayCenteredTextLine(9,"Light value is %d", light_val);
	displayCenteredTextLine(11,"Dark value is %d", dark_val);
	sleep(2500);

}
