#pragma config(Sensor, S4,     color,          sensorEV3_Color)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(long nMotorRatio, float dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
	}
}

task main()
{
	//sets the counter to 0
	int counter = 0;
	//creates an infinte loop
	while(1==1)
		{
			// checks drives forward while the sensor value is greater than 25 and thus white
			while(SensorValue(color)>30)
			{
					drive(-10,0.5,50);
			}
			// because the while loop has ended it has dectected black and increments the counter
			counter++;
			//displays the counter number
			displayTextLine(4, "%d",counter);
			//stops the motors
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			sleep(500);

			//drives while the sensor detects black
			while(SensorValue(color)<30)
			{
				drive(-10,0.5,50);
			} //end while

			writeDebugStream("Colour value is %d",SensorValue(color));

		}	//end infinite loop



}
