#pragma config(StandardModel, "RVW Anemobot")
#pragma config(RenamedStdModelMotor, motorA, armMotor)
#pragma config(RenamedStdModelSensor, S3, colorSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//drive() function
void drive(long nMotorRatio, long dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
	}	//end repeat until

}	//end drive function

task main()
{
	int i=1;




		displayCenteredBigTextLine(5,"Press enter to go");
		while(i==1)
		{
			if (getButtonPress(buttonEnter))
			{
				while(i==1)
				{

					while(SensorValue(S3)>30)
					{
						drive(50,-1,30);
						setLEDColor(ledGreen);
					}

					while(SensorValue(S3)<30)
					{
						drive(-50,-1,30);
						setLEDColor(ledOrange);
					}

				} //end inner outer while

			} //end if

		}//end outer outer while







}  //end main
