#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(long nMotorRatio, long dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
}
}
void turn90(long nMotorRatio, long power)
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		setMotorTarget(leftMotor, 186, power);
		setMotorTarget(rightMotor, 186, power);
		repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
		{
			setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1, power);
			sleep(1);
		}

}

task main()
{
	while(SensorValue(touchSensor) == 1){
		drive(4, 1, 100);
		sleep(1);
	}
	turn90(100,50);

	while(SensorValue(sonarSensor) >10)

		drive(4, 1, 50);
		sleep(1);
	}
	turn90(100,50);

	while(SensorValue(touchSensor) == 0){
		drive(0, 1, 50);
		sleep(1);
	}
	turn90(100,50);
	drive(0, 30, 50);

}
