#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//a) drive() function 
void drive(long nMotorRatio, long dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
	}	//end repeat until
	
}	//end drive function



//b) turn90() function
void turn90(long nMotorRatio, long power)
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		setMotorTarget(leftMotor, 186, power);
		setMotorTarget(rightMotor, 186, power);
		repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
		{
			setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1, power);
			sleep(1);
		}	//end repeat until

}	//end turn90()


task main()
{
		
		drive(0, 20, 50);
		turn90(-100, 50);
		
}	//end main
