#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//drive() function
void drive(long nMotorRatio, long dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
	}	//end repeat until
	
}	//end drive function



//turn90() function
void turn90(long nMotorRatio, long power)
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		setMotorTarget(leftMotor, 186, power);
		setMotorTarget(rightMotor, 186, power);
		repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
		{
			setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1, power);
			sleep(1);
		}	//end repeat until

}	//end turn90()


task main()
{
	long for_dist=100;


	drive(0,for_dist,100);	//full power straight 100cm
	
	//180 turn
	turn90(-100, 50);
	turn90(-100,50);	//2 turn 90s to turn 180
	
	//Return at 25% power
	drive(0,for_dist,25);

}
