#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//drive() function
void drive(long nMotorRatio, long dist, long power)
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	setMotorTarget(leftMotor, dist*20, 50);
	setMotorTarget(rightMotor, dist*20, 50);
	repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
	{
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 30*dist, power);
		sleep(1);
	}	//end repeat until
	
}	//end drive function



//turn90() function
void turn90(long nMotorRatio, long power)
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		setMotorTarget(leftMotor, 186, power);
		setMotorTarget(rightMotor, 186, power);
		repeatUntil(getMotorEncoder(leftMotor) >= getMotorTarget(leftMotor) ||getMotorEncoder(rightMotor) >= getMotorTarget(rightMotor))
		{
			setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1, power);
			sleep(1);
		}	//end repeat until

}	//end turn90()


task main()
{
	int i=0;
	int perimeter=240;
	long side=perimeter/4;
	int rand_number;


	rand_number=random(1);

	if(rand_number==0)
	{
		for(i=0;i<3;i++)
		{

			//Forward 3 times
			drive(0,side,50);	

			//Turn 3 times
			turn90(100,62);

		}	//end for loop

		//Final move forward
		drive(0,side,50);

	}	//end if
	else
	{
		for(i=0;i<3;i++)
		{

			//Forward 3 times
			drive(0,side,50);

			//Turn 3 times
			turn90(-100,50);

		}	//end for

		//Final move forward
		drive(0,side,50);

	}	//end else


}
