#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Move forward at half power for 5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(5000);			//Wait for 5 seconds before continuing on in the program.

	//180 turn
	setMotorSpeed(leftMotor, 77);	//Set the leftMotor (motor1) to 77% power forward
	setMotorSpeed(rightMotor, 0); 	//Set the rightMotor (motor6) to 0 to allow turn
	sleep(950);			//Wait for 0.95 seconds before continuing on in the program.

	// Move forward at half power for 5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(5000);			//Wait for 5 seconds before continuing on in the program.

}
