#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moverobot(long nMotorRatio, long time, long power){
	setMotorSyncTime(leftMotor, rightMotor, nMotorRatio, time, power);
	sleep(time);
}

task main()
{
	//part 1 square and return to position
	int i=0;
	for(i=0;i<3;i++)
	{
		//Forward
		moverobot(0,1000,50);
		moverobot(0,100,0);
		//Turn
		moverobot(76,632,49);
	}
	//Forward
	moverobot(0,1000,50);
	moverobot(0,100,0);

	//part 2 using random() function
	moverobot(random(78), random(4000),random (100));
	moverobot(0,100,0);
	//part 3

	//Move forward full power for 5s
	moverobot(0,5000,100);
	//180 turn
	moverobot(100,800,77);
	//Return at full power for 5s
	moverobot(0,5000,100);


}
